services:
  go-web-app:
    image: cosmtrek/air
    working_dir: /src
    ports:
      - "80:80"
    volumes:
      - ./:/src/
      - ./cmd/rest/main.go:/src/main.go
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: be-mistar
      POSTGRES_USER: be-mistar
      POSTGRES_PASSWORD: be-mistar
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: